### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.flume.ChannelFactory.getClass

### ISSUE THREAD

**Issue by aelsherbeeny** [Tanzu-Solutions-Engineering/flume-lib#1]
Hi,
I followed all the steps till I reached the step of starting the flume agent

flume-ng agent -n twitter -f ~/Twitter/twitter-agent.properties

however, I am getting the below error , I tried all the workarounds, but everytime it fails with the same error
# 

e:/usr/lib/gphd/hadoop/lib/native org.apache.flume.node.Application -n twitter -f /home/gpadmin/Twitter/twitter-agent.properties
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/gphd/flume/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/gphd/flume/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/gphd/flume/lib/pivotal-flume-lib-0.0.1-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
WARNING: org.apache.hadoop.metrics.jvm.EventCounter is deprecated. Please use org.apache.hadoop.log.metrics.EventCounter in all the log4j.properties files.
14/12/22 21:31:03 INFO node.PollingPropertiesFileConfigurationProvider: Configuration provider starting
14/12/22 21:31:03 INFO node.PollingPropertiesFileConfigurationProvider: Reloading configuration file:/home/gpadmin/Twitter/twitter-agent.properties
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Added sinks: HDFSSink Agent: twitter
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Processing:HDFSSink
14/12/22 21:31:03 INFO conf.FlumeConfiguration: Post-validation flume configuration contains configuration for agents: [twitter]
14/12/22 21:31:03 INFO node.AbstractConfigurationProvider: Creating channels
14/12/22 21:31:03 ERROR node.PollingPropertiesFileConfigurationProvider: Unhandled error
java.lang.NoSuchMethodError: org.apache.flume.ChannelFactory.getClass(Ljava/lang/String;)Ljava/lang/Class;
    at org.apache.flume.node.AbstractConfigurationProvider.getOrCreateChannel(AbstractConfigurationProvider.java:236)
    at org.apache.flume.node.AbstractConfigurationProvider.loadChannels(AbstractConfigurationProvider.java:199)
    at org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:101)
    at org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:140)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
^C14/12/22 21:34:03 INFO lifecycle.LifecycleSupervisor: Stopping lifecycle supervisor 10
14/12/22 21:34:03 INFO node.PollingPropertiesFileConfigurationProvider: Configuration provider stopping

**Comment by matt2000** [comment]
FWIW at this point, I had this issue with using the maven shader plugin. Once I removed that, causing Flume's own jars to be used, things worked.
